services:
  stalwart-alias:
    image: python:3.14-alpine
    working_dir: /usr/app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/usr/app/src
      - ./hot-reload.py:/usr/app/hot-reload.py
    command: python3 -u hot-reload.py
    environment:
      - IS_DOCKER=1
      - PYTHONUNBUFFERED=1
